# -*- coding: utf-8 -*-
"""Forca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Em72p934N_i6KkxsI6mA1uZdZtPPZQAj
"""

def jogar:

  print("*********************************")
  print("***Bem vindo ao jogo de Forca!***")
  print("*********************************")



  print ("Fim do Jogo")

if (__name__=="__main__"):
  jogar()